[package]
name = "sys_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
sysinfo = "0.30.3"
tui = "0.19.0"
